<?php
$VEHICLE_TYPE = [
    "CONTRACT CARRIAGE/PASSENGER VEHICLES",
    "PRIVATE SERVICE VEHICLE",
    "GOODS VEHICLE",
    "STAGE CARRIAGE",
    "CONSTRUCTION EQUIPMENT VEHICLE",
    "TEMPORARY REGISTERED VEHICLE"
];
